### ISSUE TITLE
syntax error when attempting to import  expremigen.io.pat2midi

### ISSUE THREAD

**Issue by rabarar** [shimpe/expremigen#1]
When I attempt to import the a package, I get a syntax error in the constants on line 37 of
constants.py - the return value is reporting a syntax error. 

```
return f"D{cc_number}"
```

**Comment by shimpe** [comment]
Are you using a recent version of python3?

**Comment by rabarar** [comment]
```
>>> sys.version
'3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25) \n[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]'
```

do you require 3.6? I'm using osx - i'll try using brew's python over apple's -- Turns out that that's the issue. Thx!

**Comment by shimpe** [comment]
f-strings are introduced in 3.6 indeed
