### ISSUE TITLE
MISPEL language spec

### ISSUE THREAD

**Issue by rabarar** [shimpe/expremigen#3]
is there a language spec for MISPEL? Rather than attempting to infer the intention in the examples, it would be very helpful to have a language spec document. For example, given the phrase

``` 
 c2_8*2/3\vol{fff}\tempo[120] e g b_8 c3 e g b_4 \vol{f}
```

how would I repeat it an arbitrary number of times?

**Comment by shimpe** [comment]
I'm afraid there's no built-in repeat mechanism (nor a language spec, unless you dare to interpret the raw parser grammar ;) ) at the moment. For repeats you'd have to write the same list of symbols multiple times ("unroll the loop"). 

While working on this project, I mostly was thinking about having something that can be used as a back-end for other programs (i.e. non-realtime)

I'm not sure what your use case is, but if you wanted to interactively/dynamically generate expressive MIDI in real-time, you may also want to consider taking a look at a system like supercollider instead.

**Comment by rabarar** [comment]
I have no use-case. I was just playing around with algo-generated music and tripped across your code - it's exceptional!
