### ISSUE TITLE
MISPEL incompatible with textX 1.7.0 and higher

### ISSUE THREAD

**Issue by michaelhauser** [shimpe/expremigen#5]
Tests and examples that call Mispel() fail with recent textX releases, presumably due to a change made in textX 1.7.0:
"Backward incompatible change: match filters and object processors unified."

**Comment by shimpe** [comment]
Ouch, I will need to look into that. Thanks for the notification.

**Comment by shimpe** [comment]
The problem should be fixed now.

**Comment by michaelhauser** [comment]
Fixed. Thanks!
